---
apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "local-disks-postgres"
  namespace: "openshift-local-storage"
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ocpsno.davenet.local
  storageClassDevices:
    - storageClassName: "local-sc-postgres"
      volumeMode: Filesystem
      fsType: xfs
      devicePaths:
        - /dev/vg01/postgres-data
---
apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "local-disks-workers"
  namespace: "openshift-local-storage"
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ocpsno.davenet.local
  storageClassDevices:
    - storageClassName: "local-sc-workers"
      volumeMode: Filesystem
      fsType: xfs
      devicePaths:
        - /dev/vg01/workers-data
---
apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "local-disks-redis"
  namespace: "openshift-local-storage"
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ocpsno.davenet.local
  storageClassDevices:
    - storageClassName: "local-sc-redis"
      volumeMode: Filesystem
      fsType: xfs
      devicePaths:
        - /dev/vg01/redis-data
